### PR TITLE
Create FUNDING.yml

### PR DESCRIPTION
**Pull request by lsmith77**
link to https://opencollective.com/symfony-diversity

### CODE REVIEW

**Comment by stof** [comment]
should it be in a `.github` subfolder to be consistent with the main repo ?

**Comment by lsmith77** [comment]
I don’t expect our repo to ever get a large number of top level files/dirs, so imho its clearer to have this file on the top level

**Comment by fabpot** [comment]
If we can move it under `.github`, let's do it. We do have a lot of files already, and there is already another PR adding `SECURITY.md`

**Comment by lsmith77** [comment]
@fabpot are you mixing this up with another repo? this is the diversity repo

**Comment by fabpot** [comment]
oops, sorry :) I thought it was on the main `symfony/symfony` repo.

**Pull request merged**
